USE BlueBookDB;

CREATE LOGIN user1 WITH PASSWORD = '';
CREATE USER user1 FOR LOGIN user1;
GRANT INSERT, SELECT, UPDATE ON Guardian TO user1;
GRANT INSERT, SELECT, UPDATE ON GuardianAccountDetails TO user1;
GRANT INSERT, SELECT, UPDATE, DELETE ON Child TO user1;
GRANT INSERT, SELECT, DELETE ON GuardianLanguage TO user1;
GRANT INSERT, SELECT, UPDATE  ON Address TO user1;
GRANT INSERT, SELECT, UPDATE ON Parent TO user1;
GRANT INSERT, SELECT ON familyHealthHistory TO user1;
GRANT INSERT, SELECT ON FamilyDentalHistory TO user1;
GRANT INSERT, SELECT ON ProgressNotes TO user1;
GRANT INSERT, SELECT ON IllnessInjuries TO user1;
GRANT INSERT, SELECT, UPDATE ON UsefulContact TO user1;
GRANT INSERT, SELECT ON ImmunisationRecord to user1;
GRANT INSERT, SELECT ON FourMonthImmunisation to user1;
